owner: pythoniaweb # GitHub username
repo: boomstatus # GitHub repository name
sites: # List of endpoints to track
  - name: Main
    url: http://boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Client Area
    url: http://area.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: cPanel
    url: https://cpanel.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: BoomHost FTP
    url: http://ftp.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Node 1
    url: http://order.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Node 2
    url: http://order.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
status-website: # Status website (optional)
  baseUrl: /boomstatus # Custom domain CNAME
  name: BoomHost Status # Status website title
